### ISSUE TITLE
Add a composer.json

### ISSUE THREAD

**Issue by timcv** [hipspay/woocommerce-checkout-module#4]
Hi,

Could you please include a composer.json file to your repo so i can use composer to install the plugin?
This would be a bare minimum:
`
{
  "name": "hipspay/woocommerce-checkout-module",
  "type": "wordpress-plugin",
  "require": {
    "composer/installers": "*"
  }
}
`

You can read more here:
http://selfteach.me/install-wordpress-plugins-composer/

Another option would be to submit the plugin to wordpress official plugin repository:
https://wordpress.org/plugins

**Comment by codemnkey** [comment]
Composer file added
