### ISSUE TITLE
Notice: Undefined variable: log_entry

### ISSUE THREAD

**Issue by timcv** [hipspay/woocommerce-checkout-module#5]
Notice: Undefined variable: log_entry in /home/uffeshop/sites/test.uffeshoppshop.se/releases/20190128175436/web/app/plugins/woocommerce-checkout-module-master/includes/shortcodes/class-wc-hips-shortcode-checkout.php on line 560

Change:
`$log_entry .= $text . ': ' . print_r( $message, true );`
to
`$log_entry .= $text . ': ' . print_r( $message, true );`

I tested this on php 7.2.

//Tim

**Comment by codemnkey** [comment]
Hi @timsamuelsson 
Thank you for submitting, but what am I missing. Is not the lines identical?

**Comment by timcv** [comment]
Oh, sorry, the .= should be changed to =

I think that PHP complaints because of the concatenation to a non existing variable.

**Comment by codemnkey** [comment]
Fixed in version 1.1.4
